try {
  let a;
  console.log(a.length);
  console.log("inside try statement");
} catch (e) {
  console.log("inside catch statement");
}

console.log("hi there");
